# app/routers/insights.py
"""
AI Insights endpoints - the visibility layer.

Insights are generated by app/services/insight_engine.py (statistical, no
LLM for this first pass) and reviewed here. Generation is manually triggered
for the demo rather than scheduled.
"""

import logging
from math import ceil
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import desc
from sqlalchemy.orm import Session

from ..core.database import get_db
from ..models.audit import AuditCategory, AuditSeverity
from ..models.insight import Insight, InsightSeverity, InsightStatus, InsightType
from ..schemas.insight import (
    InsightActionResponse,
    InsightGenerateResponse,
    InsightListResponse,
    InsightResponse,
)
from ..security import get_current_user
from ..services import insight_engine
from ..services.audit import audit

log = logging.getLogger(__name__)

router = APIRouter(prefix="/ai/insights", tags=["AI Insights"])


def _apply_insight_filters(query, filters: dict):
    """Apply filters to an insight query. Reused for listing and future export."""
    if filters.get("insight_type"):
        query = query.filter(Insight.insight_type == filters["insight_type"])
    if filters.get("severity"):
        query = query.filter(Insight.severity == filters["severity"])
    if filters.get("status"):
        query = query.filter(Insight.status == filters["status"])
    return query


@router.get("", response_model=InsightListResponse)
async def list_insights(
    # Pagination
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(50, ge=1, le=100, description="Items per page"),
    # Filters
    insight_type: Optional[InsightType] = Query(None, description="Filter by insight type"),
    severity: Optional[InsightSeverity] = Query(None, description="Filter by severity"),
    status: Optional[InsightStatus] = Query(None, description="Filter by review status"),
    # Dependencies
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """List insights with filtering and pagination, newest first."""
    query = db.query(Insight)

    filters = {
        "insight_type": insight_type.value if insight_type else None,
        "severity": severity.value if severity else None,
        "status": status.value if status else None,
    }
    query = _apply_insight_filters(query, filters)

    total = query.count()

    offset = (page - 1) * page_size
    items = query.order_by(desc(Insight.created_at)).offset(offset).limit(page_size).all()

    total_pages = ceil(total / page_size) if total > 0 else 1

    return InsightListResponse(
        items=[InsightResponse.model_validate(item) for item in items],
        total=total,
        page=page,
        page_size=page_size,
        total_pages=total_pages,
    )


@router.post("/generate", response_model=InsightGenerateResponse)
async def generate_insights(
    domain: Optional[str] = Query(None, description="Limit generation to one domain; omit for all domains"),
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Run the insight engine now.

    Derives patterns, anomalies, and recommendations from recent policy
    evaluation and workbench resolution activity. Manually triggered — see
    app/services/insight_engine.py for what it looks at.
    """
    insights = await insight_engine.generate_insights(db, domain=domain)
    return InsightGenerateResponse(
        generated_count=len(insights),
        insights=[InsightResponse.model_validate(insight) for insight in insights],
    )


@router.post("/{insight_id}/dismiss", response_model=InsightActionResponse)
async def dismiss_insight(
    insight_id: int,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Dismiss an insight — an operator decided it doesn't need action."""
    insight = db.query(Insight).filter(Insight.id == insight_id).first()
    if not insight:
        raise HTTPException(status_code=404, detail="Insight not found")

    if insight.status == InsightStatus.DISMISSED.value:
        raise HTTPException(status_code=400, detail="Insight is already dismissed")

    previous_status = insight.status
    insight.status = InsightStatus.DISMISSED.value
    db.commit()
    db.refresh(insight)

    await audit.log(
        action="insight.dismiss",
        description=f"Insight #{insight.id} ({insight.title}) dismissed",
        actor=user,
        category=AuditCategory.ADMIN,
        severity=AuditSeverity.INFO,
        resource_type="insight",
        resource_id=insight.id,
        resource_name=insight.title,
        metadata={"previous_status": previous_status, "new_status": insight.status},
    )

    return InsightActionResponse(
        success=True,
        insight_id=insight.id,
        action="dismiss",
        message=f"Insight '{insight.title}' dismissed",
    )
